[phases.setup]
# Explicitly use Node.js 22
nixPkgs = ["nodejs_22"]

[phases.install]
# Attempt a very clean install. 
cmds = ["npm install --production"]

[phases.build]
cmds = ["npm run build"]

[start]
# Command to start the application
cmd = "node bot.js"

[meta]
# Ensure Nixpacks respects this Node.js version
nodejs_version = "22" 